/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.51
 * Generated at: 2020-03-09 16:10:12 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views.notice;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.ArrayList;
import com.kh.notice.model.vo.Notice;
import com.kh.member.model.vo.Member;

public final class noticeListView_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/views/notice/../common/menubar.jsp", Long.valueOf(1583767311514L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.kh.notice.model.vo.Notice");
    _jspx_imports_classes.add("java.util.ArrayList");
    _jspx_imports_classes.add("com.kh.member.model.vo.Member");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");

	ArrayList<Notice> list = (ArrayList<Notice>)request.getAttribute("list");

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<style>\r\n");
      out.write("\t.outer {\r\n");
      out.write("\t\twidth:800px;\r\n");
      out.write("\t\theight:500px;\r\n");
      out.write("\t\tbackground:black;\r\n");
      out.write("\t\tcolor:white;\r\n");
      out.write("\t\tmargin:auto;\r\n");
      out.write("\t\tmargin-top:50px;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.listArea {\r\n");
      out.write("\t\tborder:1px solid white;\r\n");
      out.write("\t\ttext-align:center;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.searchArea {\r\n");
      out.write("\t\tmargin-top:50px;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.listArea > tbody > tr:hover {\r\n");
      out.write("\t\tcursor:pointer;\r\n");
      out.write("\t\tbackground:darkgray;\r\n");
      out.write("\t}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\t");
      out.write("\r\n");
      out.write("\r\n");

	Member loginUser = (Member)session.getAttribute("loginUser");

	String msg = (String)session.getAttribute("msg");
	
	String contextPath = request.getContextPath();

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<style>\r\n");
      out.write("\tbody{\r\n");
      out.write("\t\tbackground:url('");
      out.print( contextPath );
      out.write("/resources/images/eight_col_PNG2.png') no-repeat;\r\n");
      out.write("\t\tbackground-size:cover;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t/* 로그인 폼 관련 스타일 */\r\n");
      out.write("\t#loginForm, #userInfo{float:right}\r\n");
      out.write("\t.btns>button{border-radius:5px;}\r\n");
      out.write("\t#enrollBtn, #mypageBtn{background-color:yellowgreen;}\r\n");
      out.write("\t#loginBtn, #logoutBtn{background-color:orangered;}\r\n");
      out.write("\t\r\n");
      out.write("\t/* 메뉴바 영역 관련 스타일 */\r\n");
      out.write("\t.navWrap{\r\n");
      out.write("\t\tbackground-color:black;\r\n");
      out.write("\t\twidth:100%;\r\n");
      out.write("\t\theight:50px;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.nav{\r\n");
      out.write("\t\twidth:600px;\r\n");
      out.write("\t\tmargin-right:auto;\r\n");
      out.write("\t\tmargin-left:auto;\r\n");
      out.write("\t\talign:center;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.menu{\r\n");
      out.write("\t\tcolor:white;\r\n");
      out.write("\t\tfont-size:20px;\r\n");
      out.write("\t\tfont-weight:bold;\r\n");
      out.write("\t\tdisplay:table-cell;\r\n");
      out.write("\t\twidth:150px;\r\n");
      out.write("\t\ttext-align:center;\r\n");
      out.write("\t\theight:50px;\r\n");
      out.write("\t\tvertical-align:middle;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.menu:hover{\r\n");
      out.write("\t\tcursor:pointer;\r\n");
      out.write("\t\tbackground-color:darkgray;\r\n");
      out.write("\t\tcolor:orangered;\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js\"></script>\r\n");
      out.write("<script>\r\n");
      out.write("\t\r\n");
      out.write("\t// var msg = \"회원가입 성공\";\r\n");
      out.write("\tvar msg = \"");
      out.print( msg );
      out.write("\";\r\n");
      out.write("\t\r\n");
      out.write("\t$(function(){\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tif(msg != \"null\"){\r\n");
      out.write("\t\t\talert(msg);\r\n");
      out.write("\t\t\t// 세션에 담겨있는 메시지 한번만 출력하고 삭제하기\r\n");
      out.write("\t\t\t");
 session.removeAttribute("msg"); 
      out.write("\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\tfunction loginValidate(){\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tif($(\"#userId\").val().trim().length == 0){\r\n");
      out.write("\t\t\talert(\"아이디를 입력해주세요\");\r\n");
      out.write("\t\t\t$(\"#userId\").focus();\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tif($(\"#userPwd\").val().trim().length == 0){\r\n");
      out.write("\t\t\talert(\"비밀번호를 입력해주세요\");\r\n");
      out.write("\t\t\t$(\"#userPwd\").focus();\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\treturn true;\r\n");
      out.write("\t}\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\t<h1 align=\"center\">Hello!</h1>\r\n");
      out.write("\r\n");
      out.write("\t<!-- 로그인 폼 영역 -->\r\n");
      out.write("\t<div class=\"loginArea\">\r\n");
      out.write("\r\n");
      out.write("\t\t");
 if (loginUser == null) { 
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t<form id=\"loginForm\" action=\"");
      out.print(contextPath);
      out.write("/login.me\" method=\"post\" onsubmit=\"return loginValidate();\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t<table>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<th><label for=\"userId\">아이디 :</label></th>\r\n");
      out.write("\t\t\t\t\t<td><input type=\"text\" name=\"userId\" id=\"userId\"></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<th><label for=\"userPwd\">비밀번호 :</label></th>\r\n");
      out.write("\t\t\t\t\t<td><input type=\"password\" name=\"userPwd\" id=\"userPwd\"></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"btns\" align=\"center\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<button type=\"button\" id=\"enrollBtn\" onclick=\"enrollPage();\">회원가입</button>\r\n");
      out.write("\t\t\t\t<button type=\"submit\" id=\"loginBtn\">로그인</button>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\r\n");
      out.write("\t\t");
 } else { 
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t<div id=\"userInfo\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t<label>");
      out.print(loginUser.getUserName());
      out.write("님의 방문을 환영합니다.</label>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"btns\" align=\"center\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<button id=\"mypageBtn\" onclick=\"myPage();\">마이페이지</button>\r\n");
      out.write("\t\t\t\t<button id=\"logoutBtn\" onclick=\"logout();\">로그아웃</button>\r\n");
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t");
 } 
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t<script>\r\n");
      out.write("\t\tfunction logout(){\r\n");
      out.write("\t\t\tlocation.href=\"");
      out.print( request.getContextPath());
      out.write("/logout.me\";\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tfunction enrollPage(){\r\n");
      out.write("\t\t\tlocation.href=\"");
      out.print( request.getContextPath());
      out.write("/memberEnrollForm.me\";\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tfunction myPage(){\r\n");
      out.write("\t\t\tlocation.href=\"");
      out.print( request.getContextPath());
      out.write("/myPage.me\";\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tfunction goMain(){\r\n");
      out.write("\t\t\tlocation.href=\"");
      out.print( request.getContextPath());
      out.write("\";\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tfunction goNotice(){\r\n");
      out.write("\t\t\tlocation.href=\"");
      out.print( request.getContextPath());
      out.write("/list.no\";\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tfunction goBoard(){\r\n");
      out.write("\t\t\tlocation.href=\"");
      out.print( contextPath );
      out.write("/list.bo\";\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\r\n");
      out.write("\t</script>\r\n");
      out.write("\r\n");
      out.write("\t<br clear=\"both\">\t<!-- 위에 띄어진 폼 태그 뒤에 하겠음..? -->\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- 메뉴바 영역 -->\r\n");
      out.write("\t<div class=\"navWrap\">\t<!-- 메뉴바 전체 감싸는 영역 -->\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<div class=\"nav\">\t<!-- 메뉴  감싸는 영역 -->\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t<div class=\"menu\" onclick=\"goMain();\">HOME</div>\r\n");
      out.write("\t\t\t<div class=\"menu\" onclick=\"goNotice();\">공지사항</div>\r\n");
      out.write("\t\t\t<div class=\"menu\" onclick=\"goBoard();\">일반게시판</div>\r\n");
      out.write("\t\t\t<div class=\"menu\" onclick=\"\">사진게시판</div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t<div class=\"outer\">\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<br>\r\n");
      out.write("\t\t<h2 align=\"center\">공지사항</h2>\r\n");
      out.write("\t\t<br>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<table class=\"listArea\" align=\"center\">\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t<thead>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<th>글번호</th>\r\n");
      out.write("\t\t\t\t\t<th width=\"300\">글제목</th>\r\n");
      out.write("\t\t\t\t\t<th width=\"100\">작성자</th>\r\n");
      out.write("\t\t\t\t\t<th>조회수</th>\r\n");
      out.write("\t\t\t\t\t<th width=\"100\">작성일</th>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t</thead>\r\n");
      out.write("\t\t\t<tbody>\r\n");
      out.write("\t\t\t\t<!--\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td>3</td>\r\n");
      out.write("\t\t\t\t\t<td>마지막 공지사항 제목</td>\r\n");
      out.write("\t\t\t\t\t<td>admin</td>\r\n");
      out.write("\t\t\t\t\t<td>10</td>\r\n");
      out.write("\t\t\t\t\t<td>2020-02-10</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td>2</td>\r\n");
      out.write("\t\t\t\t\t<td>두번째 공지사항 제목</td>\r\n");
      out.write("\t\t\t\t\t<td>admin</td>\r\n");
      out.write("\t\t\t\t\t<td>200</td>\r\n");
      out.write("\t\t\t\t\t<td>2020-02-01</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td>1</td>\r\n");
      out.write("\t\t\t\t\t<td>첫번째 공지사항 제목</td>\r\n");
      out.write("\t\t\t\t\t<td>admin</td>\r\n");
      out.write("\t\t\t\t\t<td>1200</td>\r\n");
      out.write("\t\t\t\t\t<td>2019-12-23</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t-->\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t");
 if(list.isEmpty()) { 
      out.write("\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td colspan=\"5\">존재하는 공지사항이 없습니다.</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t");
 } else { 
      out.write("\r\n");
      out.write("\t\t\t\t\t");
 for(Notice n : list) { 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td>");
      out.print( n.getNoticeNo() );
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td>");
      out.print( n.getNoticeTitle() );
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td>");
      out.print( n.getNoticeWriter() );
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td>");
      out.print( n.getNoticeCount() );
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td>");
      out.print( n.getNoticeDate() );
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t");
 } 
      out.write("\r\n");
      out.write("\t\t\t\t");
 } 
      out.write("\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t</tbody>\r\n");
      out.write("\t\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<form class=\"searchArea\" align=\"center\">\r\n");
      out.write("\t\t\t<select id=\"condition\" name=\"condition\">\r\n");
      out.write("\t\t\t\t<option value=\"writer\">작성자</option>\r\n");
      out.write("\t\t\t\t<option value=\"title\">제목</option>\r\n");
      out.write("\t\t\t\t<option value=\"content\">내용</option>\r\n");
      out.write("\t\t\t</select>\r\n");
      out.write("\t\t\t<input type=\"search\" name=\"search\">\r\n");
      out.write("\t\t\t<button type=\"submit\">검색하기</button>\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t");
 if(loginUser != null && loginUser.getUserId().equals("admin")) { 
      out.write("\r\n");
      out.write("\t\t<!-- loginUser는 menubar.jsp에 있기 때문에 include해서 사용할 수 있다. -->\r\n");
      out.write("\t\t\t<button type=\"button\" onclick=\"location.href='");
      out.print( contextPath );
      out.write("/insertForm.no';\">작성하기</button>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t");
 } 
      out.write("\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t<script>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$(function(){\r\n");
      out.write("\t\t\t$(\".listArea>tbody>tr\").click(function(){\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t//\t\t\ttr\t\ttd들\t\t 0번 인덱스 td\r\n");
      out.write("\t\t\t\tvar nno = $(this).children().eq(0).text();\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t// 쿼리스트링을 이용하여 get 방식으로 글 번호를 servlet으로 전달\r\n");
      out.write("\t\t\t\tlocation.href=\"");
      out.print(contextPath);
      out.write("/detail.no?nno=\" + nno;\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t});\r\n");
      out.write("\t</script>\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
