/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.51
 * Generated at: 2020-02-24 09:00:22 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views.member;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.kh.member.model.vo.Member;
import com.kh.member.model.vo.Member;

public final class myPage_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/views/member/../common/menubar.jsp", Long.valueOf(1582387127686L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.kh.member.model.vo.Member");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");

	Member mem = (Member)request.getAttribute("mem");

	String userId = mem.getUserId();
	String userPwd = mem.getUserPwd();
	String userName = mem.getUserName();
	String phone = (mem.getPhone() != null) ? mem.getPhone() : "";
	String email = (mem.getEmail() != null) ? mem.getEmail() : "";
	String address = (mem.getAddress() != null) ? mem.getAddress() : "";
	
	String[] checkedInterest = new String[6];	// 값이 있는 인덱스에 checked 문자열 넣을 예정
	
	if(mem.getInterest() != null){
		String[] interests = mem.getInterest().split(",");
		
		for(int i=0; i<interests.length; i++){
			switch(interests[i]){
			case "운동" : checkedInterest[0] = "checked"; break;
			case "등산" : checkedInterest[1] = "checked"; break;
			case "낚시" : checkedInterest[2] = "checked"; break;
			case "요리" : checkedInterest[3] = "checked"; break;
			case "게임" : checkedInterest[4] = "checked"; break;
			case "기타" : checkedInterest[5] = "checked"; break;
			}
		}
	}

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<style>\r\n");
      out.write("\t.outer{\r\n");
      out.write("\t\tbackground-color:black;\r\n");
      out.write("\t\twidth:600px;\r\n");
      out.write("\t\theight:500px;\r\n");
      out.write("\t\tcolor:white;\r\n");
      out.write("\t\tmargin-top:50px;\r\n");
      out.write("\t\tmargin-left:auto;\r\n");
      out.write("\t\tmargin-right:auto;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t#updateForm{\r\n");
      out.write("\t\twidth:100%;\r\n");
      out.write("\t\tmargin-left:auto;\r\n");
      out.write("\t\tmargin-right:auto;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t#updateForm td:nth-child(1){text-align:right}\r\n");
      out.write("\t#updateForm input{margin:3px}\r\n");
      out.write("\t\r\n");
      out.write("\t#updateBtn{background:yellowgreen;}\r\n");
      out.write("\t#pwdUpdateBtn{background:orangered;}\r\n");
      out.write("\t#deleteBtn{background:yellow;}\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t\r\n");
      out.write("\t");
      out.write("\r\n");
      out.write("\r\n");

	Member loginUser = (Member)session.getAttribute("loginUser");

	String msg = (String)session.getAttribute("msg");

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<style>\r\n");
      out.write("\tbody{\r\n");
      out.write("\t\tbackground:url('");
      out.print( request.getContextPath() );
      out.write("/resources/images/eight_col_PNG2.png') no-repeat;\r\n");
      out.write("\t\tbackground-size:cover;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t/* 로그인 폼 관련 스타일 */\r\n");
      out.write("\t#loginForm, #userInfo{float:right}\r\n");
      out.write("\t.btns>button{border-radius:5px;}\r\n");
      out.write("\t#enrollBtn, #mypageBtn{background-color:yellowgreen;}\r\n");
      out.write("\t#loginBtn, #logoutBtn{background-color:orangered;}\r\n");
      out.write("\t\r\n");
      out.write("\t/* 메뉴바 영역 관련 스타일 */\r\n");
      out.write("\t.navWrap{\r\n");
      out.write("\t\tbackground-color:black;\r\n");
      out.write("\t\twidth:100%;\r\n");
      out.write("\t\theight:50px;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.nav{\r\n");
      out.write("\t\twidth:600px;\r\n");
      out.write("\t\tmargin-right:auto;\r\n");
      out.write("\t\tmargin-left:auto;\r\n");
      out.write("\t\talign:center;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.menu{\r\n");
      out.write("\t\tcolor:white;\r\n");
      out.write("\t\tfont-size:20px;\r\n");
      out.write("\t\tfont-weight:bold;\r\n");
      out.write("\t\tdisplay:table-cell;\r\n");
      out.write("\t\twidth:150px;\r\n");
      out.write("\t\ttext-align:center;\r\n");
      out.write("\t\theight:50px;\r\n");
      out.write("\t\tvertical-align:middle;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.menu:hover{\r\n");
      out.write("\t\tcursor:pointer;\r\n");
      out.write("\t\tbackground-color:darkgray;\r\n");
      out.write("\t\tcolor:orangered;\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js\"></script>\r\n");
      out.write("<script>\r\n");
      out.write("\t\r\n");
      out.write("\t// var msg = \"회원가입 성공\";\r\n");
      out.write("\tvar msg = \"");
      out.print( msg );
      out.write("\";\r\n");
      out.write("\t\r\n");
      out.write("\t$(function(){\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tif(msg != \"null\"){\r\n");
      out.write("\t\t\talert(msg);\r\n");
      out.write("\t\t\t// 세션에 담겨있는 메시지 한번만 출력하고 삭제하기\r\n");
      out.write("\t\t\t");
 session.removeAttribute("msg"); 
      out.write("\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\tfunction loginValidate(){\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tif($(\"#userId\").val().trim().length == 0){\r\n");
      out.write("\t\t\talert(\"아이디를 입력해주세요\");\r\n");
      out.write("\t\t\t$(\"#userId\").focus();\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tif($(\"#userPwd\").val().trim().length == 0){\r\n");
      out.write("\t\t\talert(\"비밀번호를 입력해주세요\");\r\n");
      out.write("\t\t\t$(\"#userPwd\").focus();\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\treturn true;\r\n");
      out.write("\t}\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\t<h1 align=\"center\">Hello!</h1>\r\n");
      out.write("\r\n");
      out.write("\t<!-- 로그인 폼 영역 -->\r\n");
      out.write("\t<div class=\"loginArea\">\r\n");
      out.write("\r\n");
      out.write("\t\t");
 if (loginUser == null) { 
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t<form id=\"loginForm\" action=\"");
      out.print(request.getContextPath());
      out.write("/login.me\" method=\"post\" onsubmit=\"return loginValidate();\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t<table>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<th><label for=\"userId\">아이디 :</label></th>\r\n");
      out.write("\t\t\t\t\t<td><input type=\"text\" name=\"userId\" id=\"userId\"></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<th><label for=\"userPwd\">비밀번호 :</label></th>\r\n");
      out.write("\t\t\t\t\t<td><input type=\"password\" name=\"userPwd\" id=\"userPwd\"></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"btns\" align=\"center\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<button type=\"button\" id=\"enrollBtn\" onclick=\"enrollPage();\">회원가입</button>\r\n");
      out.write("\t\t\t\t<button type=\"submit\" id=\"loginBtn\">로그인</button>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\r\n");
      out.write("\t\t");
 } else { 
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t<div id=\"userInfo\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t<label>");
      out.print(loginUser.getUserName());
      out.write("님의 방문을 환영합니다.</label>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"btns\" align=\"center\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<button id=\"mypageBtn\" onclick=\"myPage();\">마이페이지</button>\r\n");
      out.write("\t\t\t\t<button id=\"logoutBtn\" onclick=\"logout();\">로그아웃</button>\r\n");
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t");
 } 
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t<script>\r\n");
      out.write("\t\tfunction logout(){\r\n");
      out.write("\t\t\tlocation.href=\"");
      out.print( request.getContextPath());
      out.write("/logout.me\";\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tfunction enrollPage(){\r\n");
      out.write("\t\t\tlocation.href=\"");
      out.print( request.getContextPath());
      out.write("/memberEnrollForm.me\";\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tfunction myPage(){\r\n");
      out.write("\t\t\tlocation.href=\"");
      out.print( request.getContextPath());
      out.write("/myPage.me\";\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\r\n");
      out.write("\t</script>\r\n");
      out.write("\r\n");
      out.write("\t<br clear=\"both\">\t<!-- 위에 띄어진 폼 태그 뒤에 하겠음..? -->\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- 메뉴바 영역 -->\r\n");
      out.write("\t<div class=\"navWrap\">\t<!-- 메뉴바 전체 감싸는 영역 -->\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<div class=\"nav\">\t<!-- 메뉴  감싸는 영역 -->\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t<div class=\"menu\" onclick=\"\">HOME</div>\r\n");
      out.write("\t\t\t<div class=\"menu\" onclick=\"\">공지사항</div>\r\n");
      out.write("\t\t\t<div class=\"menu\" onclick=\"\">일반게시판</div>\r\n");
      out.write("\t\t\t<div class=\"menu\" onclick=\"\">사진게시판</div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t\t<div class=\"outer\">\r\n");
      out.write("\t\r\n");
      out.write("\t\t<br>\r\n");
      out.write("\t\t<h2 align=\"center\">마이페이지</h2>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<form id=\"UpdateForm\" method=\"post\" action=\"");
      out.print( request.getContextPath() );
      out.write("/update.me\">\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t<table>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td width=\"200px\">* 아이디</td>\r\n");
      out.write("\t\t\t\t\t<td><input type=\"text\" name=\"userId\" value=\"");
      out.print(userId );
      out.write("\" readonly></td>\r\n");
      out.write("\t\t\t\t\t<td width=\"200px\"></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td>* 이름</td>\r\n");
      out.write("\t\t\t\t\t<td><input type=\"text\" name=\"userName\" value=\"");
      out.print(userName );
      out.write("\"></td>\r\n");
      out.write("\t\t\t\t\t<td></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td>연락처 :</td>\r\n");
      out.write("\t\t\t\t\t<td><input type=\"tel\" name=\"phone\" value=\"");
      out.print(phone );
      out.write("\" placeholder=\"(-없이)01012345678\"></td>\r\n");
      out.write("\t\t\t\t\t<td></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td>이메일 :</td>\r\n");
      out.write("\t\t\t\t\t<td><input type=\"email\" name=\"email\" value=\"");
      out.print(email);
      out.write("\"></td>\r\n");
      out.write("\t\t\t\t\t<td></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td>주소 :</td>\r\n");
      out.write("\t\t\t\t\t<td><input type=\"text\" name=\"address\" value=\"");
      out.print(address);
      out.write("\"></td>\r\n");
      out.write("\t\t\t\t\t<td></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td>취미 :</td>\r\n");
      out.write("\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t<input type=\"checkbox\" name=\"interest\" value=\"운동\" id=\"sports\" ");
      out.print( checkedInterest[0] );
      out.write(">\r\n");
      out.write("\t\t\t\t\t\t<label for=\"sports\">운동</label>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<input type=\"checkbox\" name=\"interest\" value=\"등산\" id=\"climbing\" ");
      out.print( checkedInterest[1] );
      out.write(">\r\n");
      out.write("\t\t\t\t\t\t<label for=\"climbing\">등산</label>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<input type=\"checkbox\" name=\"interest\" value=\"낚시\" id=\"fishing\" ");
      out.print( checkedInterest[2] );
      out.write(">\r\n");
      out.write("\t\t\t\t\t\t<label for=\"fishing\">낚시</label>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<input type=\"checkbox\" name=\"interest\" value=\"요리\" id=\"cooking\" ");
      out.print( checkedInterest[3] );
      out.write(">\r\n");
      out.write("\t\t\t\t\t\t<label for=\"cooking\">요리</label>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<input type=\"checkbox\" name=\"interest\" value=\"게임\" id=\"game\" ");
      out.print( checkedInterest[4] );
      out.write(">\r\n");
      out.write("\t\t\t\t\t\t<label for=\"game\">게임</label>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<input type=\"checkbox\" name=\"interest\" value=\"기타\" id=\"etc\" ");
      out.print( checkedInterest[5] );
      out.write(">\r\n");
      out.write("\t\t\t\t\t\t<label for=\"etc\">기타</label>\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t<td></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t\t<br>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<div class=\"btns\" align=\"center\">\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\t<button type=\"submit\" id=\"updateBtn\">수정하기</button>\r\n");
      out.write("\t\t\t\t<button type=\"button\" id=\"pwdUpdateBtn\" onclick=\"updatePwd();\">비밀번호 변경</button>\r\n");
      out.write("\t\t\t\t<button type=\"button\" id=\"deleteBtn\" onclick=\"deleteMember();\">탈퇴하기</button>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t<script>\r\n");
      out.write("\t\tfunction updatePwd(){\r\n");
      out.write("\t\t\t//window.open(\"");
      out.print(request.getContextPath());
      out.write("/views/member/updatePwdForm.jsp\", \"비밀번호 변경창\", \"width=500, height=300\");\r\n");
      out.write("\t\t\twindow.open(\"");
      out.print( request.getContextPath());
      out.write("/updatePwdForm.me\", \"비밀번호 변경창\", \"width=500, height=300\");\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tfunction deleteMember(){\r\n");
      out.write("\t\t\tvar pwd = prompt(\"현재 비밀번호를 입력하세요\");\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tif(pwd == \"");
      out.print( userPwd );
      out.write("\"){\r\n");
      out.write("\t\t\t\tvar bool = confirm(\"탈퇴하시겠습니까?\");\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tif(bool){\r\n");
      out.write("\t\t\t\t\tlocation.href = \"");
      out.print( request.getContextPath() );
      out.write("/delete.me\";\r\n");
      out.write("\t\t\t\t} else{\r\n");
      out.write("\t\t\t\t\talert(\"취소되었습니다.\");\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t} else{\r\n");
      out.write("\t\t\t\talert(\"비밀번호를 잘못 입력하였습니다.\");\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t</script>\r\n");
      out.write("\t\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
